@hackaton_microsoft_agro_HostAddress = https://localhost:7044

### Classify Image
POST {{hackaton_microsoft_agro_HostAddress}}/classify_pest?url=https://bugwoodcloud.org/images/1536x1024/1453261.jpg
Content-Type: application/json

### Classify HealthCheck
GET {{hackaton_microsoft_agro_HostAddress}}/health

